services:
  user:
    container_name: user-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8087:80
    env_file:
      - ./.env
networks:
  default:
    name: couch-potatoes-network
    external: true
