services:
  user:
    container_name: user-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8087:80
    env_file:
      - ./.env
    volumes:
      - ./service-account-key.json:/usr/local/service-account-key.json
networks:
  default:
    name: couch-potatoes-network
    external: true
