# start with docker compose up --build or use rider
services:
  movieinformation:
    container_name: movieinformation-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    env_file:
      - ./.env

networks:
  default:
    # Remember to create this network prior to starting the service: docker network create couch-potates-network
    name: couch-potatoes-network
    external: true
