services:
  Metrics:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 8082:80
    env_file:
    - ./.env
networks:
  default:
    name: couch-potatoes-network
    external: true
