name: Continuous integration pipeline

on:
  push:
    branches:
      - 'main'
    paths:
      - src/Services/MovieInformation/MovieInformation.*/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Install Dependencies
        working-directory: src/Services/MovieInformation
        run: dotnet restore

      - name: Build
        working-directory: src/Services/MovieInformation
        run: dotnet build -c Release --no-restore

      - name: Run Tests
        working-directory: src/Services/MovieInformation
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: dotnet test
