name: Movieinformation CI/CD flow

on:
  push:
    branches:
      - 'main'
    paths:
      - src/Services/MovieInformation/MovieInformation.*/**
      - src/Services/Movieinformation/Dockerfile

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Install Dependencies
        working-directory: src/Services/MovieInformation
        run: dotnet restore

      - name: Build
        working-directory: src/Services/MovieInformation
        run: dotnet build -c Release --no-restore

      - name: Run Tests
        working-directory: src/Services/MovieInformation
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: dotnet test

  build-and-publish-image:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup docker
        uses: docker/setup-buildx-action@v2

      #TODO: (mibui 2023-05-19) Ensure these secrets has been added to the Github repository. Ping Kutaiba about this.
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        run: docker build -t "$DOCKERHUB_USERNAME"/couch-potatoes-sep6-movieinformation-service:latest .
        working-directory: src/Services/MovieInformation
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Push image
        run: docker push "$DOCKERHUB_USERNAME"/couch-potatoes-sep6-movieinformation-service:latest
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
